### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by faris-mobile89** [kudoleh/iOS-Modular-Architecture#2]
Is it possible to use Swift Package manager instead of cocoapods?

**Comment by kudoleh** [comment]
Sure it is possible to use  Swift Package manager or Carthage. In the end they are just a tools to manage dependencies and help to split app in to modules. The concept is still the same.

**Comment by kudoleh** [comment]
So this template is using CocoaPods. But it can be easily changed to Swift Package manager.
But, for this we would need to create another repo with template that uses Swift Package manager. Or add it inside this repo in the folder "Example using Swift Package manager".
