### ISSUE TITLE
one project two targets 

### ISSUE THREAD

**Issue by Prince2k3** [kudoleh/iOS-Modular-Architecture#3]
I would like to use this setup. I have a project currently that I am working in that has two app targets with. shared codebase. How can I have lib dependencies with multi targets for the different app targets? How would the Podfile look?

**Comment by kudoleh** [comment]
Hi,

Just add these lines to the Podfile:

```
target 'App2' do
  use_frameworks!
  # Pods for App
  development_pods
end
```

<img width="530" alt="Screenshot 2020-02-27 at 21 49 31" src="https://user-images.githubusercontent.com/6785311/75490013-3ca5cd00-59ab-11ea-9004-6b490f5c6cff.png">

<img width="648" alt="Screenshot 2020-02-27 at 21 54 02" src="https://user-images.githubusercontent.com/6785311/75490239-b76ee800-59ab-11ea-9ceb-209f6e7bcd30.png">

**Comment by kudoleh** [comment]
Here is real example: 
[iOS-Modular-Architecture.zip](https://github.com/kudoleh/iOS-Modular-Architecture/files/4264274/iOS-Modular-Architecture.zip)
