### ISSUE TITLE
Navigation between feature modules

### ISSUE THREAD

**Issue by mukesh-mt** [kudoleh/iOS-Modular-Architecture#7]
How to support navigation between feature modules without having them depend on each other?

**Comment by kudoleh** [comment]
We use Dependency inversion principle:
For example there is moduleA, and ModuleB and ModuleA wants to present screen from ModuleB. 

Then we create public protocol inside ModuleA: 
public protocol Router { func presentScreenFromB(fromController:)  }

Inside ModuleB we create public final class Router { func presentScreenFromB (fromController:) { ... implementation }

In Main app 
We make conformance to protocol: 
extension ModuleB.Router: ModuleA.Router {}
and now when we create ModuleA we can inject into it ModuleB.Router class
